name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install root dependencies
      run: npm ci || npm install
      
    - name: Install server dependencies
      run: cd server && npm ci || npm install
      
    - name: Check server syntax
      run: cd server && npx eslint . --ext .js || echo "ESLint not configured, skipping lint"
      
    - name: Check server startup
      run: |
        cd server
        cp .env.example .env
        node -e "try { require('./server'); console.log('Server loaded successfully!'); } catch (e) { console.error('Server failed to load:', e); process.exit(1); }"

  build:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        
    - name: Install dependencies
      run: npm ci || npm install
      
    - name: Install server dependencies
      run: cd server && npm ci || npm install
      
    - name: Verify public directory
      run: |
        if [ ! -d "public" ]; then
          echo "Public directory missing!"
          exit 1
        fi
        if [ ! -f "public/index.html" ]; then
          echo "index.html missing!"
          exit 1
        fi
        
    - name: Create deployment package
      run: |
        # Create a deployment package if you want to use it later
        # This is just an example, modify as needed
        mkdir -p deploy
        cp -r public server package.json package-lock.json README.md .gitignore deploy/
        # Exclude node_modules
        echo "Deployment package created" 